#!/bin/bash

echo "Assuming make is installed"

echo "Build the targets..."

make all

echo "Pulling test Docker images..."

MYSQL_VERSIONS="5.5.59 5.7.23 8.0.12 $MYSQL_VERSIONS"

for v in $MYSQL_VERSIONS;
do
  docker pull mysql:$v
done

NAME="nscott-debug"
for v in $MYSQL_VERSIONS;
do
  echo "Running probe against MySQL $v"
	docker run -d -e MYSQL_ROOT_PASSWORD=evian --name $NAME -p 3306:3306 mysql:$v

  echo "Waiting 30s for MySQL to start listening..."
  sleep 30

  make run
  docker rm -f $NAME
done


